version: '3.8'

services:
  app:
    build: .
    container_name: trains-app
    ports:
      - "8035:8080"
    environment:
      - SERVER_PORT=8009
      - SPRING_DATASOURCE_URL=jdbc:postgresql://trains-postgres:5432/trains_db
      - SPRING_DATA_REDIS_HOST=trains-redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=trains-kafka:9092
    depends_on:
      trains-postgres:
        condition: service_healthy
      trains-redis:
        condition: service_started
      trains-kafka:
        condition: service_started

  trains-postgres:
    image: 'postgres:latest'
    container_name: trains-postgres
    environment:
      - POSTGRES_DB=trains_db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=trains_user
    ports:
      - '5444:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U trains_user -d trains_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      # ВАЖНО: Убираем /data в конце пути для совместимости с 18+
      - trains_postgres_data:/var/lib/postgresql

  trains-redis:
    image: 'redis:latest'
    container_name: trains-redis
    ports:
      - '6399:6379'

  trains-zookeeper:
    image: 'confluentinc/cp-zookeeper:7.5.0'
    container_name: trains-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2185
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2185:2185'

  trains-kafka:
    image: 'confluentinc/cp-kafka:7.5.0'
    container_name: trains-kafka
    depends_on:
      - trains-zookeeper
    ports:
      - '9097:9095'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: trains-zookeeper:2185
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://trains-kafka:9092,EXTERNAL://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  trains_postgres_data: